Code coverage for password management
splunk/splunk-operator pull request #179
Opened 2020-11-13 19:27 UTC by akondur

Changes to improve code coverage for password management. Added coverage to secret utils, ApplyIdxcSecret and ApplyShcSecret.

2020-11-24 19:16 UTC, sgontla requested changes

2020-11-24 19:47 UTC, sgontla approved these changes
Actually, your change also covers any future errors introduced, so approving it.

2020-11-24 20:32 UTC, gaurav-splunk approved these changes
Just put some minor comments, looks good otherwise.

2020-11-24 20:32 UTC, gaurav-splunk commented on pkg/splunk/enterprise/indexercluster.go
> +			return fmt.Errorf("Couldn't find secret in Pod %s", indexerPodName)
Nit: Use `PodSecretNotFoundError` instead of the whole string?

2020-11-24 20:32 UTC, gaurav-splunk commented on pkg/splunk/enterprise/indexercluster.go
> +			return fmt.Errorf("Couldn't retrieve idxc_secret from secret data")
nit: use `SecretTokenNotRetrievable` here?

2020-11-24 22:46 UTC, akondur commented on pkg/splunk/enterprise/indexercluster_test.go
> +	}
If it returns any other error we fail the unit test, stating the error we returned.

2020-11-24 22:46 UTC, akondur commented on pkg/splunk/enterprise/indexercluster_test.go
> +	}
Replied [here](https://github.com/splunk/splunk-operator/pull/179/files#r529797052)

2020-11-24 22:46 UTC, akondur commented on pkg/splunk/enterprise/indexercluster_test.go
> +	}
Replied [here](https://github.com/splunk/splunk-operator/pull/179/files#r529797052)

2020-11-24 22:46 UTC, akondur commented on pkg/splunk/enterprise/indexercluster_test.go
> +	}
Replied [here](https://github.com/splunk/splunk-operator/pull/179/files#r529797052)

2020-11-24 22:46 UTC, akondur commented on pkg/splunk/enterprise/searchheadcluster_test.go
> +	}
Generic error handling might not catch false positives as per our discussion before. :)

2020-11-25 20:27 UTC, smohan-splunk approved these changes

2020-11-25 20:28 UTC, merged