Documentation review
splunk/splunk-operator pull request #275
Opened 2021-03-10 17:22 UTC by eddikay

ChangeLog.md - No changes. - Inbound links: Readme.md
Contributing.md - No changes. - Inbound links: None. Add from Readme.md
CustomResources.md - No changes.
OpenShift.md - No changes. It's a bit thin, but maybe there's no other detail required? - Inbound links: Readme.md
Faq.md - Remove. The only viable content remains is a quip about why HELM wasn't used.
README.md - Significant changes
Install.md - Cleanup
Images.md - Cleanup
StorageClass.md - Cleanup
Ingress.md - Adding numbers to procedures.
SmartStore.md - No changes.
PasswordManagement.md - No changes.
Examples.md -  No changes.
MultisiteExamples.md - No changes.

2021-03-11 23:53 UTC, smohan-splunk approved these changes

2021-03-11 23:53 UTC, smohan-splunk commented on docs/Images.md
> +## A Simple Script to Push Images
A "Sample" Script?

2021-03-12 20:24 UTC, vebken-splunk commented
Seems like there are some merge conflicts to resolve, I'm assuming they are mostly relating to removal of Spark from the docs.

2021-03-12 20:26 UTC, vebken-splunk commented on docs/Images.md
> +If your Kubernetes workers have access to pull from a Private registry, it is easy to retag and push the required images to directly to the private registry.
nit: not related to your change specifically, but we have inconsistent capitalization between "Private registry" and "private registry"

2021-03-12 20:31 UTC, vebken-splunk commented on docs/Images.md
> +A sample script `build/push_images.sh`  is included with the opertor to push Docker images to multiple remote hosts using SSH. The script takes the name of a container and an image path, and pushes t
nit: operator is misspelled "opertor"

2021-03-12 20:48 UTC, vebken-splunk commented
A general nitpick question I have reviewing the docs, when we are using "operator" as shorthand for "Splunk Operator" rather than the Kubernetes operator pattern, should it be capitalized?

2021-03-12 20:54 UTC, vebken-splunk commented on docs/README.md
>  modifications will be made prior to its general availability, it is not
Not related to your change, but we probably want to rewrite or remove this paragraph for GA.

2021-03-12 21:00 UTC, vebken-splunk commented on docs/README.md
>  cat <<EOF | kubectl apply -f -
We'll want to update the apiVersion in the example to v1 per https://github.com/splunk/splunk-operator/pull/274

2021-03-12 21:06 UTC, vebken-splunk commented
For all yaml examples, we should update the apiVersion to v1 per #274

2021-03-12 21:13 UTC, vebken-splunk commented on docs/StorageClass.md
> +The [introduction](https://kubernetes.io/blog/2018/01/introducing-container-storage-interface/) of Kubernetes’s [Container Storage Interface](https://kubernetes.io/blog/2019/01/15/container-storage-i
nit: "encouraged to take a review the Kubernetes" -> "encouraged to review the Kubernetes"

2021-03-12 21:29 UTC, vebken-splunk commented on docs/Ingress.md
>  [NGINX Ingress Controller GitHub repository](https://github.com/nginxinc/kubernetes-ingress/) and the [Installation Guide](https://kubernetes.github.io/ingress-nginx/deploy/).
This line needs to be modified https://github.com/nginxinc/kubernetes-ingress/ should be replaced with https://github.com/kubernetes/ingress-nginx

2021-03-17 19:26 UTC, mgaldino-splunk approved these changes

2021-03-17 19:41 UTC, vebken-splunk requested changes

2021-03-17 19:41 UTC, vebken-splunk commented on docs/Images.md
> +A sample script `build/push_images.sh`  is included with the opertor to push Docker images to multiple remote hosts using SSH. The script takes the name of a container and an image path, and pushes t
This typo still seems to remain in the new commit.

2021-03-17 20:11 UTC, vebken-splunk approved these changes

2021-03-17 20:25 UTC, merged

2021-03-17 21:04 UTC, akondur approved these changes