CSPL-1458: Fixing failing C3 appframework test
splunk/splunk-operator pull request #583
Opened 2021-11-11 01:15 UTC by jambrosiano

- Scaling test: Adding missing app upload for C3
- Scaling test: Removing unnecessary v1 apps upload
- Scaling test: removing redundant lines
- Redistributing smoke and integration tests

2021-11-16 21:48 UTC, tpereirasplunk approved these changes

2021-11-16 23:25 UTC, pdhanoyasplunk commented on test/c3/appframework/appframework_test.go
>  			managerPodNames := []string{fmt.Sprintf(testenv.ClusterManagerPod, deployment.GetName()), fmt.Sprintf(testenv.DeployerPod, deployment.GetName())}
`managerPodNames` is same as `podNames`

2021-11-17 00:54 UTC, pdhanoyasplunk requested changes

2021-11-17 00:54 UTC, pdhanoyasplunk commented on test/c3/appframework/appframework_test.go
> +		It("integration, c3, appframework: can deploy a C3 SVA instance with App Framework enabled and install above 200MB of apps at once", func() {
Cleanup lIne 1388 by declaring shReplicas := 3
and replace code on 1405 with allpodNames

2021-11-17 00:57 UTC, pdhanoyasplunk commented on test/c3/appframework/appframework_test.go
> +			testenv.VerifyAppsCopied(deployment, testenvInstance, testenvInstance.GetName(), []string{mcPodName}, appListV2, true, true)
clusterwide set to true for MC verification should be false.

2021-11-17 00:57 UTC, pdhanoyasplunk commented on test/c3/appframework/appframework_test.go
> +			testenv.VerifyAppInstalled(deployment, testenvInstance, testenvInstance.GetName(), []string{mcPodName}, appListV2, true, "enabled", true, true)
Clusterwide set to true for Monitoring console

2021-11-17 00:59 UTC, pdhanoyasplunk commented on test/c3/appframework/appframework_test.go
> +			testenv.VerifyAppInstalled(deployment, testenvInstance, testenvInstance.GetName(), []string{mcPodName}, appListV1, true, "enabled", false, true)
Clusterwide set to true for MC.

2021-11-17 01:59 UTC, pdhanoyasplunk commented on test/c3/appframework/appframework_test.go
> +		It("integration, c3, appframework: can deploy a C3 SVA instance with App Framework enabled and install above 200MB of apps at once", func() {
I see the code on line 1405 is still there .. We have function to generate these 
```
allPodNames = append(allPodNames, testenv.GeneratePodNameSlice(testenv.SearchHeadPod, deployment.GetName(), shReplicas, false, 1)...)
			
allPodNames = append(allPodNames, testenv.GeneratePodNameSlice(testenv.IndexerPod, deployment.GetName(), indexerReplicas, false, 1)...)
```

2021-11-17 03:29 UTC, pdhanoyasplunk commented on test/c3/appframework/appframework_test.go
> +			testenvInstance.Log.Info("Verify apps are installed on the Indexers and Searc Heads")
NIT: `Searc Heads` vs `Search Heads`

2021-11-17 17:46 UTC, pdhanoyasplunk approved these changes

2021-11-18 00:09 UTC, smohan-splunk approved these changes

2021-11-18 00:09 UTC, merged