CSPL-1419: use different App Source for every CR for M4 test cases
splunk/splunk-operator pull request #603
Opened 2021-11-26 04:37 UTC by jambrosiano

Added different AppFramework sources for each CR(IDXC and SHC)

Passed tests:
[1] • [SLOW TEST:1660.371 seconds]
[1] m4appfw test
[1] /Users/jambrosiano/splunk-operator/develop/splunk-operator/test/m4/appframework/appframework_test.go:30
[1]   Multisite Indexer Cluster with Search Head Cluster (m4) with App Framework
[1]   /Users/jambrosiano/splunk-operator/develop/splunk-operator/test/m4/appframework/appframework_test.go:298
[1]     integration, m4, appframework: can deploy a M4 SVA with App Framework enabled, install apps and downgrade them
[1]     /Users/jambrosiano/splunk-operator/develop/splunk-operator/test/m4/appframework/appframework_test.go:299
[1] ------------------------------
[1] • [SLOW TEST:980.434 seconds]
[1] m4appfw test
[1] /Users/jambrosiano/splunk-operator/develop/splunk-operator/test/m4/appframework/appframework_test.go:30
[1]   Multi Site Indexer Cluster with Search Head Cluster (m4) with App Framework)
[1]   /Users/jambrosiano/splunk-operator/develop/splunk-operator/test/m4/appframework/appframework_test.go:764
[1]     integration, m4, appframework: can deploy a M4 SVA and have apps installed locally on Cluster Manager and Deployer
[1]     /Users/jambrosiano/splunk-operator/develop/splunk-operator/test/m4/appframework/appframework_test.go:765
[1] ------------------------------
[1] {"level":"info","ts":1637897575.467571,"msg":"testenv deleted.\n","testenv":"m4appfw-un4"}
[1] {"level":"info","ts":1637897575.467602,"msg":"testenv deleted.\n","testenv":"m4appfw-un4"}
[1]
[1] JUnit report was created: /Users/jambrosiano/splunk-operator/develop/splunk-operator/test/m4/appframework/m4appfw-un4_junit.xml
[1]
[1] Ran 2 of 2 Specs in 2657.405 seconds
[1] SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 0 Skipped
[1] PASS
[2] • [SLOW TEST:1476.361 seconds]
[2] m4appfw test
[2] /Users/jambrosiano/splunk-operator/develop/splunk-operator/test/m4/appframework/appframework_test.go:30
[2]   Multisite Indexer Cluster with Search Head Cluster (m4) with App Framework
[2]   /Users/jambrosiano/splunk-operator/develop/splunk-operator/test/m4/appframework/appframework_test.go:61
[2]     smoke, m4, appframework: can deploy a M4 SVA with App Framework enabled, install apps and upgrade them
[2]     /Users/jambrosiano/splunk-operator/develop/splunk-operator/test/m4/appframework/appframework_test.go:62
[2] ------------------------------
[2] • [SLOW TEST:1889.689 seconds]
[2] m4appfw test
[2] /Users/jambrosiano/splunk-operator/develop/splunk-operator/test/m4/appframework/appframework_test.go:30
[2]   Multisite Indexer Cluster with Search Head Cluster (m4) with App Framework
[2]   /Users/jambrosiano/splunk-operator/develop/splunk-operator/test/m4/appframework/appframework_test.go:536
[2]     integration, m4, appframework: can deploy a M4 SVA with App Framework enabled, install apps, scale up clusters, install apps on new pods, scale down
[2]     /Users/jambrosiano/splunk-operator/develop/splunk-operator/test/m4/appframework/appframework_test.go:537
[2] ------------------------------
[2] {"level":"info","ts":1637898299.7345579,"msg":"testenv deleted.\n","testenv":"m4appfw-b98"}
[2] {"level":"info","ts":1637898299.7345998,"msg":"testenv deleted.\n","testenv":"m4appfw-b98"}
[2]
[2] JUnit report was created: /Users/jambrosiano/splunk-operator/develop/splunk-operator/test/m4/appframework/m4appfw-b98_junit.xml
[2]
[2] Ran 2 of 2 Specs in 3381.666 seconds
[2] SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 0 Skipped
[2] PASS

2021-11-27 01:19 UTC, pdhanoyasplunk commented on test/testenv/deployment.go
>  	if d.testenv.licenseFilePath != "" {
Unrelated change. Need to edit like 691 to `_, err := d.DeployLicenseManager(licenseMaster)`

2021-11-27 01:23 UTC, pdhanoyasplunk requested changes

2021-11-27 01:23 UTC, pdhanoyasplunk commented on test/m4/appframework/appframework_test.go
> +			appSourceNameMC := "appframework-" + enterpriseApi.ScopeLocal + "mc-" + testenv.RandomDNSName(3)
This can be moved to BeforeEach.

2021-11-27 01:23 UTC, pdhanoyasplunk commented on test/m4/appframework/appframework_test.go
> +			appSourceVolumeNameMC := "appframework-test-volume-mc-" + testenv.RandomDNSName(3)
Same.This can be moved to BeforeEach.

2021-11-29 19:30 UTC, smohan-splunk approved these changes

2021-11-29 22:17 UTC, tpereirasplunk approved these changes

2021-11-29 22:28 UTC, pdhanoyasplunk approved these changes

2021-11-29 22:28 UTC, pdhanoyasplunk commented on test/m4/appframework/appframework_test.go
> +			appSourceVolumeNameMC := "appframework-test-volume-mc-" + testenv.RandomDNSName(3)
Rename `appSourceVolumeNameMC` to `volumeNameMC`

2021-11-29 22:28 UTC, pdhanoyasplunk commented on test/m4/appframework/appframework_test.go
> +			appSourceVolumeNameMC := "appframework-test-volume-mc-" + testenv.RandomDNSName(3)
Rename `appSourceVolumeNameMC` to `volumeNameMC`

2021-11-30 18:59 UTC, merged