Edit and remove redundant cases
splunk/splunk-operator pull request #948
Opened 2022-10-21 16:19 UTC by tpereirasplunk

2022-10-21 19:51 UTC, gaurav-splunk approved these changes

2022-10-26 22:04 UTC, pdhanoya-splunk requested changes

2022-10-27 16:58 UTC, pdhanoya-splunk commented on test/appframework_aws/c3/manager_appframework_test.go
> +			testenv.VerifyNoDisconnectedSHPresentOnCM(ctx, deployment, testcaseEnvInst)
As I requested please verify once manually and close CSPL-619 with comments.

2022-11-01 00:31 UTC, jambrosiano commented on test/delete_cr/deletecr_test.go
> +			Expect(err).To(Succeed(), "Unable to get Indexer instance")
Message is about Indexer, but this is SHC

2022-11-01 00:32 UTC, jambrosiano commented on test/delete_cr/deletecr_test.go
> +			// Delete Search Head Cluster CR
This says SHC, but this is about CM

2022-11-01 20:29 UTC, jambrosiano approved these changes

2022-11-01 22:18 UTC, merged